### ISSUE TITLE
Complete with absolute path

### ISSUE THREAD

**Issue by backuitist** [pantsbuild/intellij-pants-plugin#147]
Currently if I have a project with the following structure:
```
- some\long\path\lang\BUILD
- some\long\path\io\BUILD
- some\long\path\stuff\BUILD
```
it will take a few completion strokes before you get the complete path:
`so<caret>` + `<TAB>`
`some\lo<caret>` + `<TAB>`
`some\long\pa<caret>` + `<TAB>`
`some\long\path\st<caret>` + `<TAB>`

I suggest we shorten this by offering the absolute path:
`st<caret>` + `<TAB>` => `some\long\path\stuff`

**Comment by wisechengyi** [comment]
I like the idea, but i think there's also a few concerns.

1. The existing ways to suggest path incrementally is canonical, so at least we shouldn't remove this option.
2. I assume in order to suggest the full paths, it is functionally doing in pseudocode:
```
(find <current folder>).filter(x: 'stuff' in x.filename)
``` 
Another option is to show everything that contains 'stuff' within the full paths. so both `some\long\path\stuff` and `some\long\stuff\path` will show up. Then add some ordering mechanism.
3. Pants is used in very large repos, so the range of the scan may matter a lot, ideally we want to have some mechanism so that if the number of files exceeds some threshold, fall back to the canonical way.

**Comment by backuitist** [comment]
I've submitted a PR, and I'll open a RB ticket soon. About your concerns:

1. agreed.
2. agreed, I haven't added any ordering a.t.m but I believe the segments come first. Note that the filtering is done by intellij.
3. see 1. and 2.

**Comment by wisechengyi** [comment]
1. be sure to create a RB
2. Regarding #3. i haven't checked out https://github.com/pantsbuild/intellij-pants-plugin/pull/154/ and played with it, but just heads up that what intellij does may not be optimal. Assume there is close to 1 million files under the build root, you might want to mock it out to get a feel how fast/slow it is. From the look of the PR, there is no heuristic regarding that yet.

**Comment by backuitist** [comment]
Right, 1 million... has the plugin been tested with such a large amount of BUILD files? I wonder what `pants export ::` looks like?

**Comment by wisechengyi** [comment]
it's unlikely `pants export ::` will happen for any project, but for the BUILD file search it is needed.

**Comment by backuitist** [comment]
The way it works now filters out files that do not belong to the project, meaning that if you've got a huge project and only a fraction of it has been loaded in the IDE, then only that fraction will be provided by the completion provider.
Now if you want to load your project from the root, which is what I do as I have < 200 BUILD files, the plugin will issue a `pants export ::`.
So the bottom line is, either you load lots of BUILD files and you'll have other performance concerns, or you have a reasonable amount of BUILD files and that'll work just fine :)

**Comment by backuitist** [comment]
>  for the BUILD file search it is needed

This PR makes use of intellij file indexing.
