### ISSUE TITLE
Support for IntelliJ IDEA 2017.1 EAP

### ISSUE THREAD

**Issue by kiRach** [pantsbuild/intellij-pants-plugin#269]
Any chance to support new EAP?

**Comment by wisechengyi** [comment]
Normally we do not support EAP because we release from master, which means if EAP has breaking/backwards incompatibile changes, which they do in this case, we will stop the support for earlier versions. 

That said, we have it prepared at https://github.com/pantsbuild/intellij-pants-plugin/pull/237, and I can give you a temp build if you want.

**Comment by kiRach** [comment]
@wisechengyi I see that #237 was merged but I can't find "Pants" in the list of the plugins for IDEA 2017

![](https://i.gyazo.com/3451b5919db40625dad9d43a958bc478.png)

**Comment by wisechengyi** [comment]
@kiRach we haven't done a release yet, but you can manually download the build at https://plugins.jetbrains.com/plugin/7412-pants-support bleedingedge channel, aka, master.

**Comment by tispratik** [comment]
Thanks, installed the bleeding edge version for 17.1.

**Comment by wisechengyi** [comment]
https://github.com/pantsbuild/intellij-pants-plugin/releases/tag/release_1.6.0
