### ISSUE TITLE
Make plugin compatible with PyCharm

### ISSUE THREAD

**Issue by thesamet** [pantsbuild/intellij-pants-plugin#291]
Currently this plugin is not available in PyCharm - it's not listed in the list of plugins. 

When installing from disk the plugin is marked as red in the plugins list since the dependencies for scala, junit and so on are unmet.

**Comment by wisechengyi** [comment]
'Pants Support` currently has direct code dependency on Gradle, JUnit, and Scala plugins, unless they are separated out of the code base, running it in pycharm wouldn't be feasible. 

Alternatively, you can use intellij idea + python plugin which is almost equivalent to pycharm.

**Comment by wisechengyi** [comment]
Unfortunately I cannot get this prioritized at the moment, but PR is always welcome :)

**Comment by danieljanes** [comment]
Are there any plans to support PyCharm?

**Comment by wisechengyi** [comment]
Marking as 'wont fix', but feel free to reopen if anyone is going to actively work on it. The TODO is to extract/copy the dependency on gradle. https://github.com/pantsbuild/intellij-pants-plugin/blob/bced5c6da49dc6875c5b9ed5353c2651c737041a/resources/META-INF/plugin.xml#L21

**Comment by Gerrit-K** [comment]
I'm not very familiar with the JetBrains Products' plugin framework, so I don't exactly understand why it's not possible / feasible to model this via plugin dependencies. But having an IDE plugin for a build system focussed on **Python** that is only supported by the vendor's **Java**-IDE instead of the **Python**-IDE doesn't seem right.

I know that IntelliJ is by far their most used IDE and works well for Python with the official Python plugin, but there's a reason for PyCharm to exist and many Python developers prefer this over the "generic" IDE. 

Is there a chance to revise this decision? Perhaps something changed in the meantime, which makes the implementation easier :)

**Comment by wisechengyi** [comment]
pants plugin currently has code dependency on gradle plugin (e.g. using it's test console and what not). Since gradle plugin isn't available for pycharm, pants plugin won't work there either.

So the last comment on TODO is still relevant, which is to move/remove the dependency on gradle plugin.

Twitter likely cannot prioritize this, but PR is still welcome.

**Comment by Gerrit-K** [comment]
> Since gradle plugin isn't available for pycharm [...]

Doesn't seem like it isn't:
![image](https://user-images.githubusercontent.com/8766565/99790974-33562500-2b25-11eb-8fc7-1cd15b74dbc4.png)
Or did I misunderstand the issue?

Anyways, I (sadly) understand that this might not get prioritized. However, providing a PR will take a rather large amount of time for me due to learning the language, framework and plugin structure. I'll try to find the time, but if anyone else with more experience wants to chime in I'd appreciate that very much :)
