### ISSUE TITLE
Plugin doesn't set up Scala SDK

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/intellij-pants-plugin#90]
After importing a scala project from a BUILD file, I get the following message from IntelliJ: "No Scala SDK in module", and there's a link to click to set one up.  Pants knows the Scala version, so it should be possible to set this up automatically.

**Comment by wisechengyi** [comment]
1. IntelliJ 15.0.1 has a known bug for that. 
2. Otherwise I cannot reproduce with examples/src/scala/org/pantsbuild/example/hello. SDK is found automatically as below:
![screen shot 2015-12-23 at 1 27 55 pm](https://cloud.githubusercontent.com/assets/596358/11985377/0bc6e6e2-a979-11e5-9468-a3d51451e9ce.png)

**Comment by benjyw** [comment]
This is on IntelliJ 14.X

**Comment by wisechengyi** [comment]
14 stopped getting updates since 501660c7b289b74ae27e5c7b1800cc4a338439bb

According to the readme:
"As of 12/10/2015, latest version of the plugin only works with IntelliJ IDEA 15.0.0 and >=15.0.2. Do not use 15.0.1."
